#!/bin/bash

echo "🔧 Configurando PostgreSQL para work-machine-viewer..."

echo "📋 Execute os seguintes comandos no terminal:"
echo ""
echo "1. Configure a senha do usuário postgres:"
echo "   sudo -u postgres psql -c \"ALTER USER postgres PASSWORD 'postgres';\""
echo ""
echo "2. Crie o banco de dados:"
echo "   sudo -u postgres createdb work_machine_viewer"
echo ""
echo "3. Teste a conexão:"
echo "   psql -h localhost -U postgres -d work_machine_viewer -c \"SELECT 1;\""
echo ""
echo "4. Aplique as migrações:"
echo "   psql -h localhost -U postgres -d work_machine_viewer -f migrations/init.sql"
echo ""
echo "5. Inicie o projeto:"
echo "   npm run dev"
echo ""
echo "💡 Dica: Se der erro de autenticação, tente:"
echo "   sudo -u postgres psql"
echo "   \\password postgres"
echo "   (digite 'postgres' como senha)"
echo "   \\q"
