#!/bin/bash

echo "🖥️ Instalando pgAdmin - Interface Gráfica para PostgreSQL"
echo "========================================================"
echo ""

echo "📦 Opções de instalação:"
echo ""
echo "1️⃣ Via Snap (mais fácil):"
echo "   sudo snap install pgadmin4"
echo ""
echo "2️⃣ Via apt (Ubuntu/Debian):"
echo "   sudo apt update"
echo "   sudo apt install pgadmin4"
echo ""
echo "3️⃣ Via Flatpak:"
echo "   flatpak install flathub org.pgadmin.pgadmin4"
echo ""
echo "4️⃣ Via Docker (recomendado):"
echo "   docker run -p 5050:80 -e PGADMIN_DEFAULT_EMAIL=admin@admin.com -e PGADMIN_DEFAULT_PASSWORD=admin dpage/pgadmin4"
echo ""

echo "🔧 Após instalar:"
echo "   - Acesse: http://localhost:5050 (Docker) ou abra o pgAdmin"
echo "   - Adicione servidor: localhost:5432"
echo "   - Usuário: postgres"
echo "   - Senha: postgres"
echo "   - Banco: work_machine_viewer"
echo ""

echo "🌐 Alternativas web:"
echo "   - Adminer: https://www.adminer.org/"
echo "   - phpPgAdmin: sudo apt install phppgadmin"
