// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmqwwqodawvhqvkwmdhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptcXd3cW9kYXd2aHF2a3dtZGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTQxODksImV4cCI6MjA3NDM5MDE4OX0.RL9CesFWZFcYn9ggOGCn2BnT5NXbx2OCigxzN3gAnm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});